server:
  port: 8080

spring:
  application:
    name: banco-austro

datasources:
  cuenca:
    url: jdbc:postgresql://localhost:5442/banco_cuenca
    username: banco
    password: banco123
    driver-class-name: org.postgresql.Driver
  quito:
    url: jdbc:postgresql://localhost:5443/banco_quito
    username: banco
    password: banco123
    driver-class-name: org.postgresql.Driver